moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.0
project:
  name: moai-rank
  mode: personal
  description: ''
  created_at: '2026-01-19 23:43:33'
  optimized: false
  template_version: 1.14.0
